// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: adahavqipaqwbdbudmfo

class SupabaseConfig {
  static const String supabaseUrl = 'https://adahavqipaqwbdbudmfo.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkYWhhdnFpcGFxd2JkYnVkbWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNTU5NzIsImV4cCI6MjA3NzczMTk3Mn0.hm0H3liNIMANjAryOjcEtwTNM163t23adagg2sv2VZM';
}
